// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOerSHByOUSmTaC149g6PH4M3i9aCEppE',
    appId: '1:43018022643:web:099d459834d97c38d71186',
    messagingSenderId: '43018022643',
    projectId: 'lalamu-4ff90',
    authDomain: 'lalamu-4ff90.firebaseapp.com',
    storageBucket: 'lalamu-4ff90.firebasestorage.app',
    measurementId: 'G-8C53BQSQF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4jFWkQn1iktiNVXE5UZ7J6xmeKnlM9f4',
    appId: '1:43018022643:android:6f8dba9855e3dcd1d71186',
    messagingSenderId: '43018022643',
    projectId: 'lalamu-4ff90',
    storageBucket: 'lalamu-4ff90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAXV_1QCra3ZaDXSeXNrGpMs8jpYAaP8',
    appId: '1:43018022643:ios:50d335e24afa050fd71186',
    messagingSenderId: '43018022643',
    projectId: 'lalamu-4ff90',
    storageBucket: 'lalamu-4ff90.firebasestorage.app',
    iosBundleId: 'com.example.lalamuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAXV_1QCra3ZaDXSeXNrGpMs8jpYAaP8',
    appId: '1:43018022643:ios:50d335e24afa050fd71186',
    messagingSenderId: '43018022643',
    projectId: 'lalamu-4ff90',
    storageBucket: 'lalamu-4ff90.firebasestorage.app',
    iosBundleId: 'com.example.lalamuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOerSHByOUSmTaC149g6PH4M3i9aCEppE',
    appId: '1:43018022643:web:099d459834d97c38d71186',
    messagingSenderId: '43018022643',
    projectId: 'lalamu-4ff90',
    authDomain: 'lalamu-4ff90.firebaseapp.com',
    storageBucket: 'lalamu-4ff90.firebasestorage.app',
    measurementId: 'G-8C53BQSQF8',
  );
}
